# 模型配置
model_provider = "codex-for-me"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
disable_response_storage = false
max_context = 1000000               # 1M 上下文
context_compact_limit = 800000      # 80% 时触发压缩

network_access = "enabled"
personality = "pragmatic"
max_threads = 3
service_tier = "fast"

[features]
multi_agent = true


[agents.reviewer]
description = "Find security, correctness, improvement,and test risks in code. "
config_file = "agents/reviewer.toml"


[model_providers.codex-for-me]
name = "openai"
base_url = "https://api-vip.codex-for.me/v1"
wire_api = "responses"
requires_openai_auth = true

[projects."/home/shiyicong/temp/CongCore/os"]
trust_level = "trusted"

[projects."/home/shiyicong/temp/CongCore"]
trust_level = "trusted"

[projects."/home/shiyicong/temp"]
trust_level = "untrusted"

[projects."/home/shiyicong/temp/ai-shell"]
trust_level = "trusted"

[projects."/home/shiyicong/.codex"]
trust_level = "trusted"

[projects."/home/shiyicong/.config/nvim"]
trust_level = "trusted"

[projects."/home/shiyicong"]
trust_level = "trusted"

[projects."/home/hypertest/.codex"]
trust_level = "trusted"

[projects."/home/hypertest/.config/nvim"]
trust_level = "trusted"

[projects."/home/hypertest/temp/study"]
trust_level = "trusted"

[projects."/home/hypertest"]
trust_level = "trusted"

[projects."/home/hypertest/temp/minipack"]
trust_level = "trusted"

[projects."/home/hypertest/temp/rspack"]
trust_level = "trusted"

[projects."/home/hypertest/temp/playground"]
trust_level = "trusted"

[projects."/home/hypertest/temp/SillyTavern-Launcher"]
trust_level = "trusted"

[projects."/home/hypertest/temp"]
trust_level = "trusted"

[projects."/home/hypertest/temp/pack101"]
trust_level = "trusted"

[projects."/home/hypertest/ubuntu20-gcc7-flex-bison"]
trust_level = "trusted"

[projects."/home/hypertest/temp/work1"]
trust_level = "trusted"

[tui]
theme = "monokai-extended-light"

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.4"


# [mcp_servers.context7]
# args = [
#     "-y",
#     "@upstash/context7-mcp",
#     "--api-key",
#     "ctx7sk-0e3a1650-59dc-4a38-a166-8fb11668f45e",
# ]
# command = "npx"
# startup_timeout_ms = 20_000
